services:
  blue:
    image: "${NCP_CONTAINER_REGISTRY}/cnergy-backend:${GITHUB_SHA}"
    container_name: sarang-backend-blue
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    ports:
      - '8080:8080'
    networks:
      - sarang-backend-network

  green:
    image: "${NCP_CONTAINER_REGISTRY}/cnergy-backend:${GITHUB_SHA}"
    container_name: sarang-backend-green
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    ports:
      - '8081:8080'
    networks:
      - sarang-backend-network
