positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: application-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/my/logs/*.log