name: Sarang Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Gradle 캐시 적용
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: JDK 17 세팅
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: YML 파일 세팅 및 fcm.json 주입
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          TEST_APPLICATION_PROPERTIES: ${{ secrets.TEST_APPLICATION_PROPERTIES }}
          ERROR_MESSAGES_PROPERTIES: ${{ secrets.ERROR_MESSAGES_PROPERTIES }}
          FCM_JSON: ${{secrets.FCM_JSON}}
        run: |
          cd ./src
          rm -rf main/resources/application.yml
          mkdir -p test/resources
          mkdir -p main/resources
          mkdir -p main/resources/firebase
          echo "$APPLICATION_PROPERTIES" > main/resources/application.yml
          echo "$ERROR_MESSAGES_PROPERTIES" > main/resources/api-error-messages.properties
          echo "$FCM_JSON" > main/resources/firebase/fcm.json
          echo "$TEST_APPLICATION_PROPERTIES" > test/resources/application.yml

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: 테스트 수행
        run: ./gradlew test

      - name: 테스트 리포트 아티팩트 업로드
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: 스프링부트 빌드
        run: ./gradlew build

      - name: Docker Buildx 세팅
        uses: docker/setup-buildx-action@v3

      - name: 도커 로그
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 도커 이미지 빌드 후 푸시
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sarang-backend:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Docker Compose 파일 EC2 서버로 전송
        run: scp -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:./

      - name: Docker Compose Mornitoring 파일 EC2 서버로 전송
        run: scp -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} ./observability/docker-compose.monitoring.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/observability/

      - name: EC2 접속 후 이미지 다운로드 및 배포
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "DOCKER_CONTAINER_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "DOCKERHUB_PASSWORD=${{secrets.DOCKERHUB_PASSWORD}}" >> .env
            echo "GITHUB_SHA=${{ github.sha }}" >> .env
            echo "MINIO_ROOT_USER=${{secrets.MINIO_ROOT_USER}}" >> .env
            echo "MINIO_ROOT_PASSWORD=${{secrets.MINIO_ROOT_PASSWORD}}" >> .env
            echo "MINIO_SERVER_URL=${{secrets.MINIO_SERVER_URL}}" >> .env
            echo "MINIO_BROWSER_REDIRECT_URL=${{secrets.MINIO_BROWSER_REDIRECT_URL}}" >> .env
            echo "GF_SECURITY_ADMIN_PASSWORD=${{secrets.GF_SECURITY_ADMIN_PASSWORD}}" >> .env
            sudo chmod +x ./deploy.sh
            ./deploy.sh
